# Generated by Django 5.1.4 on 2025-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='cars/carro.png', upload_to='cars/'),
        ),
    ]
